language: php

php:
  - 5.5

before_install:
  - composer self-update
  - composer install --dev -n --prefer-source

script:
  - ./vendor/bin/phpunit

deploy:
  provider: azure_web_apps
  username: pocff       # If AZURE_WA_USERNAME isn't set
  password: Ebc12Svf   # If AZURE_WA_PASSWORD isn't set
  site: poc       # If AZURE_WA_SITE isn't set
  verbose: true
  skip_cleanup: true
