language: php
php:
- 5.5
before_install:
- composer self-update
- composer install --dev -n --prefer-source
script:
- "./vendor/bin/phpunit"
deploy:
  matrix:
  - provider: azure_web_apps
    username:
      secure: hE0uJqQHkHJXw+uYurFSvpO8pw3HYkS7clQSOHoHjp2SKmkQRgJNbgkm7sbRvsEGk2qqvSN+hWm86X+jUboc/G3BresFLKgNaiBbCOusrbD3U1J3zoh2+Sk3NMVMTdwY7xNbjciYgSd8ZXLteDgLvjWe+nmpP+IJMRfvKlbOxyGHSJs4U9y99kY/WMRb/GvYiLfzWdioPHV4l4zMFmta8uz9Ij2J0RjkUekjLfNiHiKni0+Ju7Ijyn+kJKE8jJ6MlRjwqM77mpm34/RuHnzLm/vlzVQHu1AI6ZDROuPlbxsHEOfsgwo60mARorxwJTBwZ3gG68sZmUw2PHYxIUdkKw0/2dhiw0J5RSrAZYU3r42/DcVru1iMifXeb4vb/P+Vwe3r3ZG2F3flOrIOHAN1R+TgLfDLlZChs2OtovPGSUMUxq7DQwJOVHds8KI2h22F5Xq65UVwhfwAc27fPIZrTskjnM+rfMEgww8X2m7sjjQ9UfoNuj+tnRpVHOBHiza5ca1UCOmu/Z2Z0bTzomKcjwVCl7Y4eWq324/G1v9xoZjjc1wV9FOG2E82bn3FWEg8a9R9NsYmRWPUBlJ69lX1MbIgDoFQL8D/rxKzHXOPBu+HmwsryYT7D+PCMv6XvX7lkuAyQ1H8s9ASWyo7IL1ThCv7jUJFqHyncZQ7jkS9bCc=
    password:
      secure: ZPQiuS80k+euvZi3ASfdi0g8w00CxvFhc4u2Uiz927FjxZqtGXYEK4eCBXoxZKHBlJICf6MoglA/uEmq9NCWzmIjFgNbYhUfSkdKupcZa3h7n/oATdWWMMgCECkX+0fcMYeuYDg53hVEF6CVikn80U7UfodpacdaSuhlJyfUCoWnjgHL39n9z0haXRaIarUt1LivYuIsMdc3aY9W50rJvlKDUSi1JtpvM0NEQYWCiahJ8RaWJQGYGbyBp9oA0YfYl9pdsTvYP8nDdhJurLPRTTJ1BE7jA51T/Oemm2GbCyUaDI6aknPer8t8VEHCpitq6BdeAxGchoB2jDwSyd9mmV4dzebAeZEegS8u0wneOZnHGFIJ9WPTh405hYTzYXqBpVnGE9dCCgTPBIgaGW36YKgVL+geYWhYV1K3dTMUHThb+CumWqfBzZ9C13XFmI/1bfHXjjK0PqNiTHEPhrfF580aPzeXDqS3an94140cNuQ9/YwDKkOdymCs08bL445CXQsLGBv8inX+7ETp3ktdQd9tMta010BqmBD27FmcASj7e+l2xjphcAX8nchvheeeNrBSwGHF+poXYmqbxiTE4kzgpGnvTv87ivX49JPXpEgq59DqIHu5n+OkY3GPeeP6CGg9mbhWOvCh4Ru7b9zH4qWw5qwhM+yyYUfD1EqJRJw=
    site: poc
    verbose: true
    skip_cleanup: true
  - provider: elasticbeanstalk
    app: poc
    env: devff-env
    bucket_name: elasticbeanstalk-eu-west-1-543443504517
    region: eu-west-1
    skip_cleanup: true
    verbose: true
    secret_access_key:
      secure: NzGXq7IfI0RWdChEyY01NAQUPuehz6JoCpFfEcpRwxwJhsTYlNiSiSJYWLGX3b+XBk+NA6ZggX+GB9aUlAni8cjiL6iT36SNOV6ufsg4zaf9qjAUBv3syv0BUiIN6bi3oDPgLRmSdH2/ZIcQFJsZO7kqncyiPDjIj6o3x/EwWp7bkOVMK6GbJXnAa4PIqOG02s841aWSRH7BWQRaxUENQUdqFhnVdzwDnJRRjeKl+mbtIZToYQDa4/k9gunLMMdjsD4b70X1SOx9oeKl5XeQayxtsp9a0ZeFpVe/9DvWbf2CETq0wGEnF5ZEvUGRy5QOHFqdQVulVrm1p+uOHiISO1qqf4cNPatCWRWcEGqEoh+OkhLhguK7ddouSXLRTJHXkuzjQuM3B62BUFbvvVFOX41BJRSuleM8iP+E70GuzY2mP7QUaQkpq9eqUTK7/xu5fU1MT9NqPLm1E3xkvy3gOOeb779aOeUuPrzRSlKZeFozBIrSh3cFUZxIJwAQf3UNnH1UIyMRDI160N9vP9u0BjmWcNeh4MoruCi5W261oENZeKVSx0i4kWNQIa7+N2sm3yalkbCqm/mn95e8xalawif0CS86wFfBObRVDsZsuZz2CDdt1mZjxcsUubSQ6NpGKtBuGsvhTmNvmhSqAkN/IhhTE6wOXf9qBDppusELeyQ=
    access_key_id:
      secure: FZ+Tc061XW64jdcXZjqZ7CMLYlRwxvUKGrHwT9+xeA5o8RvlRyYwuFPBC9tdzQZF9683UJpgPQvsdViP/98hdIHdMS1tCae9QYz7epLlkBp7+3fZBXg6EQ+W00Xj3V7EFzrarK4CeSTQ/vvfWYTz6gLG6++Dy8n4Lcc4AfaYf5n/0HRkiS76cpH8YYByUTpPznN7W4b9RGp/+FktrtpqA3RViqkud8ruoMEYbpPmUv4bX94sgmVnolbJbdJSWIBLlJ7OMtKrMUjtky+d39lhFUlIwU4C9OA9oXGRtYDtbo6esUYboexSOPprkQNmrefizNyHjFFBZHmhiL6DchDfKaDETuUew0qiYOl6hB/r4njY27Ki6vNDJvkDANVXvj4gFlSb1NTey4/3YhW+31ikTzOa4HafX4fq9Xy1uY0f1zkftBeDC67uSEO50wzOGWv0JdSTnsVTm0kiQKSltFIsNZN3kakMefifbFKJgrurHCezlsRmtO045fneLsAW+0RCA8O1hSnwlH8MqB9wAf75zSLZxdwkHAZ/YWMNG7QB5c6dBVGNw++N47pT2DSuaYcUWvHWzE69SRbox0Eogw4G0Dn/FvDel8ZdVzKluXFT1WFz//K5uxzXwwDxUJz9lwHwu7D05MvpCC1sKi3r2ilUakSIreolrmtmuQXrH35357k=
notifications:
  slack: bonnenuit:TM9Vpftr7I2HKD42Iey43kIQ
