language: php
php:
- 5.5
before_install:
- composer self-update
- composer install --dev -n --prefer-source
script:
- "./vendor/bin/phpunit"
deploy:
  - provider: elasticbeanstalk
    app: poc
    env: devff-env
    bucket_name: elasticbeanstalk-eu-west-1-543443504517
    region: eu-west-1
    skip_cleanup: true
    verbose: true
    secret_access_key:
      secure: gmJjg49Yjo3ecShz+EJS07yzP0Txlbt+5Z1rJRJv3xx1R2r9PN51eLSUZj71lV0P4aF/zI05Qm9azGZpHIXnrB0MXcAnra9YQSNHWGpBaNpAeJ/thK1+auj4WKOQ9G1iCwG0zpn9wAEjkoWOgtcrsLGN+AzY9W1evZgZVp8FPrQJdb7F8F4Btgsy6XfB7PzqvgO2mwfiud47NqpQqw8jgmBXx06+vFlT7Y3jXLw/NxKU0zJudSq4EPiSuNyi9uqcK/oKCkjR5oxncizybx0faH2oOeMYk6TNhJ1b4nOO1HKsiBM2GE7C6yQ1ZW66JWq3lvEipE9ySXob1QUqqkOa+P28MlvJu2ls0aOW5FujdFASBzF8++2OM45vaaiTXXnbGYWSTdtWDXKiOkdgt1+fLnatQzJSWEJ5RxCSrrPRT2XTw/DbBQAaqgL3T3W1rwl1/PPI6vs5lX4efaawwgYRowUGqmTvuT6fCc26EUgYa3o3d85fw46R3WgGSmkMw/Ga8jVGOIKYaowOVA3cywdGfN0azlYCyxh64MKMsNT3euN2w4NsyRgXM4aj0EsqLJa6JVMiMJQzshvkHoBX2fNUdnR3c0Ok5XsPQYovWqwBo4nxL0JpgZ2dwCj2NvSH53Wgf4SyQTvlkHTUa0U0YEnPNLE0dtOvophX/IpqJeq3ZmM=
    access_key_id:
      secure: rQIl3yQCT9HNdN+fygYm38N2hJcf21bvKach6uK7VSDPBeYCyClcUtby1ftLMLgitnEXX8syyvOuTqvDJchp+J++CHuH0PZTEz92w7Y2FuEkrBeSUNtuzN+ZNx+9OP2r+trhyDfLvISqlQpM7js9koRZIR314ZjZIzkk3MdAO+eqffQqZ40ZzKMy9ojlGjCotm5auKN0TByLjCPUpjHm9J64SosNtSNAmNZQlefLTI/xOHUTsODZDkkrJglra86q32mRVInaG2EELRmFqLPkZYI0fr1ta4Nm38+fNQy9tqcYkbQAFlCtGOIa9fFFV2W56S/COLb53Jrv4aG3SLFm1RudkBXgnfnE2soSSbFErgm3MQRzUqnzWkwm6OjYBxZHxRHDE1r8qHoENU7/oKjPjBnXfoSU//gq8exIyPlB6v24K54tTrdY7oydQTF679isUYnK2TtP7Rhg2UfOm2wSbjNqhgGGkaukPL1bZ+kMwDOVJZqx1DsdeHYvRZzk36TRYkkYvhjFDAb0fMc+CAjLrpMgklLgQLAYi7Bbpfb44tXhnqE9pOtsksNERw2qZQXyS0EQwvfKWJ51VptGGVAzjHlFL8Edofiv00TD2ux47Kr7ebZUWbHpnArxq+EvwSi0IRHx/1bpydlCAPkP+SSmL7OLpETDGHoaLcvObSv8Y3E=
notifications:
  slack: bonnenuit:TM9Vpftr7I2HKD42Iey43kIQ
